[pytest]
addopts =
    --cov-report term-missing
    --cov=src
testpaths =
    test
pythonpath = .

markers =
    demo: demonstration tests (run with '-m demo')
    unit: unit tests using mocks and isolated components (run with '-m unit')
    integration: integration tests using real database/system interaction (run with '-m integration')
    staging: unfinished or experimental tests (run with '-m staging')
    namespaces: tests for namespace challenge (run with '-m namespaces')